# 타입별 라벨 (commit type 기준)
- name: "feat"
  color: "0E8A16"
  description: "새로운 기능 추가"

- name: "fix"
  color: "D73A49"
  description: "버그 수정"

- name: "docs"
  color: "0366D6"
  description: "문서 수정"

- name: "style"
  color: "FBCA04"
  description: "코드 의미에 영향을 주지 않는 변경사항"

- name: "refactor"
  color: "5319E7"
  description: "코드 리팩토링"

- name: "perf"
  color: "F9D0C4"
  description: "성능 향상"

- name: "test"
  color: "BFD4F2"
  description: "테스트 코드 추가"

- name: "chore"
  color: "EDEDED"
  description: "빌드 부분 혹은 패키지 매니저 수정사항"

- name: "design"
  color: "FF69B4"
  description: "퍼블리싱 및 디자인 수정"

- name: "file"
  color: "8B4513"
  description: "파일 이동 및 삭제"

# 우선순위 라벨
- name: "priority: critical"
  color: "B60205"
  description: "최우선으로 처리해야 하는 이슈"

- name: "priority: high"
  color: "D93F0B"
  description: "높은 우선순위"

- name: "priority: medium"
  color: "FBCA04"
  description: "보통 우선순위"

- name: "priority: low"
  color: "0E8A16"
  description: "낮은 우선순위"

# 이슈 타입 라벨
- name: "bug"
  color: "D73A49"
  description: "버그 신고"

- name: "enhancement"
  color: "0E8A16"
  description: "새로운 기능 요청"

- name: "task"
  color: "0366D6"
  description: "개발 작업"

- name: "question"
  color: "CC317C"
  description: "질문"

# 상태 라벨
- name: "status: in-progress"
  color: "FBCA04"
  description: "진행 중"

- name: "status: review"
  color: "0366D6"
  description: "리뷰 중"

- name: "status: blocked"
  color: "D73A49"
  description: "블로킹됨"

- name: "status: duplicate"
  color: "CFD3D7"
  description: "중복"

- name: "status: wontfix"
  color: "CFD3D7"
  description: "수정하지 않음"

# 프로젝트 영역 라벨
- name: "area: frontend"
  color: "B7E5F2"
  description: "프론트엔드 관련"

- name: "area: backend"
  color: "F2E5B7"
  description: "백엔드 관련"

- name: "area: database"
  color: "E5B7F2"
  description: "데이터베이스 관련"

- name: "area: api"
  color: "B7F2E5"
  description: "API 관련"

# 난이도 라벨
- name: "difficulty: easy"
  color: "7BE16E"
  description: "쉬운 난이도"

- name: "difficulty: medium"
  color: "FBCA04"
  description: "보통 난이도"

- name: "difficulty: hard"
  color: "D73A49"
  description: "어려운 난이도"

# 특별 라벨
- name: "good first issue"
  color: "7057FF"
  description: "첫 기여자에게 좋은 이슈"

- name: "help wanted"
  color: "008672"
  description: "도움이 필요한 이슈"